# Пользовательский провизионер (JWK, ACME, SCEP, SSHPOP) — параметры настраиваются в CLI.
NAME=
TYPE=JWK
DEFAULT_DURATION=8760h
MAX_DURATION=8760h
DESCRIPTION="Custom provisioner (JWK, ACME, SCEP, SSHPOP)"
ALLOWED_DOMAINS=""
